version: '3.8' 

services: 
  db: 
    image: postgres:15 
    container_name: solvit_db 
    env_file: 
      - .env-docker 
    ports: 
      - 5433:5432 
    volumes: 
      - postgresdata:/var/lib/postgresql/data 

  solvit: 
    image: solvit_image 
    build: 
      context: . 
    container_name: solvit_app 
    env_file: 
      - .env-docker
    depends_on: 
      - db 
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000" 
    ports: 
      - 9000:8000 

volumes: 
  postgresdata:
